/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/BarChart.vue')['default']
    CanvasJSChart: typeof import('./src/components/CanvasJSChart.vue')['default']
    Estadisticas: typeof import('./src/components/Estadisticas.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MaizPredict: typeof import('./src/components/MaizPredict.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
